import React from "react";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const ShippingReturnPage = () => {
    return(
        <div>
            <Navbar />
                <div className="container p-3 text-secondary">
                    <p className="lead"><b>Shipping and Returns</b></p>
                    <p>Merchandise Returns</p>
                    <p>Here at Turts&Torts your complete satisfaction is our number one goal!</p>
                    <p>For returns made within 14 days of the initial shipment date (the initial shipment date is determined by the Ups Delivery receipt), we will issue you a refund in the form of your original payment method. For all returns made after the 14 days, but not to exceed 30 days of the initial shipment date will receive a refund in the form of a Turts&Torts Online Gift Certificate. Purchases of Online Gift Cards and Online Gift Certificates are non-refundable.</p>
                    <p>In order to expedite the return procedure; please ship item(s) and a copy of your original order. This copy can be obtained by logging into your Turts&Torts account. Once you have logged in elect to view previous orders, locate the order for the item in questions and then print the necessary order slip. Then click on the return request tab on the left and request a Return Merchandise Authorization Number. The Return Merchandise Authorization Number must be written in on the side of the returned package. The returned item(s) must be sent to Turts&Torts at the following address:</p>
                    <p>1725 Slough Avenue</p>
                    <p>Scranton, PA. 18505</p>
                    <p>Please allow 3-5 business days from merchandise receipt for your return to be processed. You will receive an email confirmation. Please allow up to 10 business days for your account balance to reflect the refund. This timeframe varies by banking institution.</p>
                    <p>If your return is the result of an error on the part of Turts&Torts, or a defective or damaged product, we will refund merchandise and shipping charges to your original form of payment or replace the merchandise free of charge. If the exact item is unavailable we will substitute the item for a similar item of equal or greater value. We will also reimburse shipping charges incurred to return damaged, defective, or incorrect merchandise to Turts&Torts, not to exceed the published Ups Ground rate for the weight of the package.</p>
                    <p>If returning merchandise for any other reason, you are required to pay all shipping charges to and from Turts&Torts. Item(s) returned that are not damaged, defective or a mistake on the part of Turts&Torts are subject to a 20% re-stocking fee.</p>
                    <p>All returns are required to include all of the original packaging and accessories. Items must be returned with proper packaging and in new condition. All returns must also accompany a Return Merchandise Authorization number, also referred to as an RMA.</p>
                    <p>For your security, please send your return via a carrier who offers package tracking such as FedEx, UPS or USPS (Note: A request for this service must be noted with USPS) (be sure to retain your tracking receipt for future reference). Turts&Torts is not responsible for lost shipments. Shipping charges are non-refundable.</p>
                    <p>Turtle Returns</p>
                    <p>Turts&Torts is the internet’s number one source for high quality Turtles. We offer only the best possible candidates to our customers for adoption. In order to accomplish this we hand select and thoroughly inspect each and every Turtle that leaves our facility. This allows us to guarantee our customers that when adopting a Turtle from the Turts&Torts you will be receiving a Turtle that is in excellent health. We are so confident that we offer a Guarantee on live arrival, in addition to a 7 Day Health Warranty. A complete copy of the Animal Guarantee is included in every Turtle shipment. Please read over the information thoroughly so as to understand what is required, in order to be covered under our Guarantee. Due to federal regulations, we are unable to accept live animal returns.</p>
                    <p>Cancellation Requests:</p>
                    <p>Orders are filled as swiftly and promptly as possible here at Turts&Torts. We understand just how valuable your time is so we waste no time satisfying your request(s) with absolute swiftness. Once a package departs with the shipping carrier there is no way to retrieve the shipment for cancellation. With this in mind, cancellation requests, on orders that contain merchandise and products, must be made within 24 hours of the date and time the order was placed.A cancellation receipt will be sent to you by email alerting you that the cancellation request has been filled so long as the request was made within 24 hours of the order being placed. A 20% cancellation/processing fee will be applied to all cancelled orders.</p>
                    <p>Unlike merchandise and product orders, a good deal of additional care is involved in preparing a Turtle for shipment. Once your order is placed, the Turtle is immediately pulled and the preparation begins. This preparation requires that the Turtle be hand selected and inspected by our specially trained staff. Then the Turtle will undergo additional cleaning, feeding and soaking to prepare it for the eminent journey that lies ahead. Next, the Turtle will be transferred to our shipping department so that they can coordinate all of the necessary shipping arrangements with Ups. Turts&Torts works closely with Ups so that they may hand deliver your package directly to your door step. Given that this process is so extensive and includes so much we are unable to allow cancellations on orders that contain Turtles.</p>
                    <p>Shipping</p>
                    <p>Turts&Torts takes great pleasure in offering you the utmost of assurance that your order will be packaged and processed for shipment as quickly as humanly possible. This is done without sacrifice to the integrity of the item(s) contained within the shipment. All orders are processed for shipment on a first come first serve basis. The following will offer greater insight into our shipping process.</p>
                    <p>Orders containing Turtles are only shipped Monday thru Wednesday; unless you have made special arrangements with us to elect for a Saturday Delivery. Saturday Deliveries are only available in select areas. An additional fee applies to a Saturday Delivery election. Turtles can only be shipped using Air Service. When using Air Services you are limiting the amount of time that the Turtle will have to spend in transit to roughly 72 hours at the most.</p>
                    <p>Orders containing products and merchandise are shipped Monday thru Friday. The service method suggested for shipment of your product and merchandise orders is U.P.S Ground Service. This service will transport your package on the Ground.</p>
                    <p>Once your payment has cleared, your order will then be filled and prepared for shipping. We do our very best to have your order shipped out within 2 to 4 business days. Nevertheless, we do reserve the right to require up to 7 to 10 business days to ship out your order. Please keep in mind that when ordering a Turtle from the Turts&Torts, just because the election is made for Air Service does not imply that the Turtle will arrive to you within 2 days of placing your order. The election for Air Service with U.P.S merely means that once the order is processed and ready to ship out to you, the package will only be in transit to it’s destination for up to 72 hours.</p>
                    <p>Once your order is placed, you will receive a confirmation email with that will contain a copy of your invoice.</p>
                    <p>Shipping costs are determined by the total weight of the order and by the shipping method selected. Your total shipping charges will be displayed on the "Review and Submit Your Order" page, prior to placing your order. Live Arrival Guarantee:</p>
                    <p>In the rare event that an animal perishes, before arriving at their destination, we will issue a store credit for the cost of the animal, provided that certain criteria are met. A valid shipping address was included on the original order. Failure to include important details regarding the shipping address will automatically void the guarantee. Including, but not limited to street names, apartment/suite numbers and zip codes. The intended recipient was available to receive their package on the first delivery attempt. All orders containing a live animal will require a signature, upon delivery. Our guarantee cannot be extended to any order left on a doorstep and not signed for. The election was made to ship the original order, containing a live animal, via Air Service. Please keep in mind that the election to ship an order containing a live animal using either Ground service will cause the Live Arrival Guarantee to become null and void. We must be notified within 2 hours of delivery. This notification must be done by email so that the time can be verified based upon UPS' proof of delivery. Telephone notification cannot be accepted, due to the time restrictions present. Use the E-Mail US Link at the bottom of the page.you will be issued a Guarantee Authorization Number or GA number. The GA number must accompany your return back to our facility. The deceased animal must be frozen and prepared for return. Your return must be postmarked for return within 2 days of receiving your GA number. We cannot be responsible for any costs incurred to exercise our guarantee. Please note all shipping fees are nonrefundable. The validity of our guarantee can only be established via notification within the necessary 2 hour time period.7 Day Health Guarantee</p>
                    <p>Our health guarantee is the best in the industry. We are so certain that all of our turtles and tortoises are of top notch quality that we stand behind their health for a full 10 days after they arrive to you. With that said, it is impossible for us to extend this guarantee beyond this point. Your care plays to much a part in　a turtle or tortoises ability to thrive beyond the 10 day period. All of the animals are screened by our Herpetology Staff, on a weekly basis. However, this in no way guarantees anything beyond what the naked eye may detect. If you have any concerns regarding the health of your turtle or tortoise you should immediately seek the assistance of a qualified veterinarian. We do not assume any responsibility for your desire to seek such assistance. In the unlikely event that a turtle or tortoise should perish within our 10 day health guarantee we will issue you a store credit for the cost of the animal. The store credit can be used at any time to cover the cost of a replacement or substitute animal(s). Please note all shipping fees are nonrefundable. The validity of our guarantee can only be established via notification within the necessary 10 day period. The 10 day period begins from the time stamp provided by UPS, also referred to as UPS' proof of delivery. Proper notification must be done via email. Use the E-Mail US Link at the bottom of the page.Telephone notification cannot be accepted, due to the time restrictions present. Any claims made outside the 10 day time frame will automatically be denied. In order for our guarantee to be honored you must meet the following criteria listed below:</p>
                    <p>Tracking Your Order</p>
                    <p>A valid shipping address was included on the original order. The validity of a shipping address is determined via UPS Worldship. Including but not limited to street names, apartment/suite numbers and zip codes. Failure to include important details regarding the shipping address will automatically void the guarantee.　 The intended recipient must have been available to receive and sign for their package on the first delivery attempt. All orders containing a live animal will require a signature, upon delivery. Our guarantee will not be extended to any order left on a doorstep and not signed for. The election was made to ship the original order, containing a live animal, via Air Service. Please keep in mind that the election to ship an order containing a live animal using either Ground service will cause the Live Arrival Guarantee to become null and void. The animal must have perished within the 7 day period. The 7 day period is determined by UPS' proof of delivery.　 The deceased animal must be frozen, in the event that a return may be necessary. You must contact us by email alerting us of your desire to request a Guarantee Authorization Number or GA number. Please us the E-Mail US Link at the bottom of the page. The GA number must accompany your return back to our facility. Your request for a GA number must be made within the 7 day time frame. No return shall be accepted without a GA number.　 Your return must be　postmarked within 2 days of receiving your GA number. We cannot be responsible for any　costs incurred to exercise our guarantee. Please note that failure to read our terms and conditions, whether or deliberate or involuntary will under no circumstances　be cause to consider them null and void. Once your order has been processed and prepared to ship, you will receive an email containing the tracking information for the shipment.　 Using your　U.p.s tracking number, you can check the status of your package by visiting　http://www.ups/tracking/tracking.html or by calling U.p.s directly at 1-800-PICK-UPS (742-5877)</p>
                    <p>You can have complete confidence that your order will be packaged with the utmost of care.</p>
                    <p>Live Animal Shipping Charges Terms & Conditions:</p>
                    <p>All live animal orders must be shipped via Ups Air Services. No order will be shipped out using U.S Mail. You agree that any order placed that contains a live animal will only be shipped via Ups Air Services and that if you place an order that contains a live animal and select U.S Mail or Ups Ground services your order will be placed on hold and not shipped until you upgrade your shipping charges. You also agree that if you do select U.S Mail or Ups Ground services as your shipping you will contact us at robertmoore@Turts&Torts for directions on how to upgrade your shipping to Ups Air Services. You agree and understand that no order maybe cancelled or refunded due to you selecting the wrong shipping service.</p>
                </div>
            <Footer />
        </div>
    )
}

export default ShippingReturnPage;